### ISSUE TITLE
Replace cljs.reader with decodn

### ISSUE THREAD

**Issue by mkremins** [mkremins/flense-nw#15]
[decodn](https://github.com/mkremins/decodn) is an alternative Clojure code reader that produces a Flense-format parse tree instead of raw Clojure forms. It also understands some constructs that cljs.reader simply doesn't, allowing us to parse (and therefore load/display) a wider range of files.

**Comment by darwin** [comment]
Just wondering. How does decond compare to https://github.com/xsc/rewrite-clj?

**Comment by mkremins** [comment]
rewrite-clj is very similar to a combination of decodn + [xyzzy](https://github.com/mkremins/xyzzy) + the core tree-manipulation parts of Flense, especially the [flense.model](https://github.com/mkremins/flense/blob/master/src/flense/model.cljs) namespace. decodn corresponds roughly to rewrite-clj's [reader](https://github.com/xsc/rewrite-clj/blob/master/src/rewrite_clj/reader.clj) and [parser](https://github.com/xsc/rewrite-clj/blob/master/src/rewrite_clj/parser.clj) namespaces in that it's simply used to extract a parse tree from Clojure source code files that can then be manipulated by Flense.

However, rewrite-clj attempts to maintain whitespace/comments/other code formatting across structural transformations. Flense doesn't care about whitespace or formatting, so decodn makes no attempt to record these aspects of the code in the parse trees it produces.

decodn is inspired most directly by [kovasb/codn](https://github.com/kovasb/codn), which extracts a parse tree that preserves a similar level of information about the source code document as decodn itself. To quote directly from the codn readme:

> It is a non-objective of codn to provide isomorphic representation of textual documents containing source code. While codn is potentially useful for IDEs and editors, the goal is not to represent the document containing the program, but the program itself.

All of these statements can generally be assumed to hold true about decodn as well.

**Comment by darwin** [comment]
Thanks a lot. I'm still trying to wrap my head around all this.
